config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  # Forregistrations_controller.rb details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, skip: :registrations, path: '',
             path_names: {sign_in: 'login',
                          sign_out: 'logout',
                          sign_up:'register',
             },
             controllers: {registrations: 'registrations'}

  # set the prefix of the path so that we can rename the path helper method
  ## BECAREFUL, USE :user insteand :users
  devise_scope :user do
    get 'login', to: 'devise/sessions#new', as: :login
    post 'login', to: 'devise/sessions#create'
    delete 'logout', to: 'devise/sessions#destroy', as: :logout
    # create user has the same path name as
    get 'register', to: 'registrations#new', as: :register
    post 'register', to: 'registrations#create'
    get '/', to: 'dashboard#index'

  end

  resources :urls

  scope ShortUrl.redirect_config.route_namespace do
    get ":url_hash", to: 'redirection#show'
  end

  namespace :reports do
    resources :short_urls, only: [:index, :show], as: :short_urls
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/locateable.rb
module Locateable
  extend ActiveSupport::Concern

  LOCATION_ATTRIBUTES = %w[ip
                          address
                          latitude
                          longitude
                          state
                          province
                          state_code
                          province_code
                          country
                          country_code]
  class Location < Struct.new(*LOCATION_ATTRIBUTES.map(&:to_sym))
    def self.build(args = {})
      args.present? ? new(*args.values_at(*LOCATION_ATTRIBUTES)) : new
    end
  end

  class_methods do
    # @param [String] ip
    # @return [Hash{String=>Object}]
    def lookup_location(ip)
      return {} unless ip
      provider = Geocoder.config.ip_lookup
      if (res = Geocoder.search(ip, ip_lookup: provider).first)
        data = LOCATION_ATTRIBUTES.each_with_object({}) do |attr, memo|
          memo[attr] = res.send(attr) if res.respond_to? attr
        end
        data["ip"] = ip
        {
          "data" => data,
          "provider" => provider&.to_s
        }
      else
        {}
      end
    end
  end
end

app/models/short_url.rb
class ShortUrl < ApplicationRecord
  belongs_to :url
  MAX_LENGTH = 15
  MIN_LENGTH = 5
  RANDOM_LENGTHS = (5..15).entries.freeze

  validates_presence_of :url_hash
  validates_uniqueness_of :url_hash
  validates_length_of :url_hash, maximum: MAX_LENGTH, minimum: MIN_LENGTH

  delegate :original_url, :title, to: :url, allow_nil: true

  # @param [Integer] length
  # @return [String]
  def self.generate_url_hash(length: nil)
    length ||= RANDOM_LENGTHS.shuffle.first
    val = SecureRandom.alphanumeric(length)
    return val if val.size == length
    val[0...length]
  end

  def self.url_hash_to_url(url_hash)
    File.join(redirect_config.host.domain, redirect_config.route_namespace, url_hash)
  end

  # @return [String]
  def to_url
    self.class.url_hash_to_url(url_hash)
  end

  # @param [Integer] length
  def generate_url_hash(length: nil)
    self.url_hash = self.class.generate_url_hash(length: length)
  end

  def self.redirect_config
    Settings.redirection
  end

  def redirect_config
    self.class.redirect_config
  end
end

app/models/url.rb
class Url < ApplicationRecord
  DEFAULT_TITLE = 'Default title'
  include Utils::UrlFormatValidation
  belongs_to :user
  has_many :short_urls

  validates_uniqueness_of :original_url
  validates_presence_of :original_url, :title
  validate :validate_url_format
  accepts_nested_attributes_for :short_urls

  def build_short_url
    short_urls.build.tap { |surl| surl.generate_url_hash }
  end

  private

  def validate_url_format
    url_format_valid?(original_url)
  end
end

app/models/url_click.rb
class UrlClick < ApplicationRecord
  include Locateable

  # @param [Hash] event
  #   @option [Time] event_time
  #   @option [String] url_hash
  #   @option [Integer] short_url_id
  #   @option [Integer] original_url_id
  def self.track(event)
    return unless event
    event_time = event[:event_time] || Time.current
    create(
      **event.slice(:url_hash, :short_url_id, :original_url_id),
      created_at: event_time, updated_at: event_time, location_details: lookup_location(event[:ip])
    )
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :urls
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  def redirect_if_not_authorize
    unless user_signed_in?
      redirect_to login_path
    end
  end

  def render_404
    render file: "#{Rails.root}/public/404", layout: false, status: :not_found
  end
end

app/controllers/authorizable_controller.rb
class AuthorizableController < ApplicationController
  before_action :redirect_if_not_authorize
  # @!method current_user
  #   @return [User]
  private

  def redirect_if_not_authorize
    unless user_signed_in?
      redirect_to login_path
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < AuthorizableController
  def index
  end
end

app/controllers/redirection_controller.rb
class RedirectionController < ApplicationController
  before_action :check_redirectable, only: :show
  after_action :track_click, only: :show

  def show
    expires_in 90, private: true
    redirect_to @original_url, status: :moved_permanently
  end

  private

  def track_click
    return unless @original_url
    UrlClick.track(
      url_hash: @short_url.url_hash, short_url_id: @short_url.id, original_url_id: @short_url.url_id,
      ip: client_ip
    )
  end

  # Add additional rules here if necessary
  def check_redirectable
    @short_url = ShortUrl.find_by_url_hash(params[:url_hash])
    @original_url = @short_url&.original_url
    render('show', locals: { request_url: request.url }, layout: 'application_public', status: 404) unless @original_url
  end

  def client_ip
    request.headers['HTTP_X_FORWARDED_FOR']&.split(',')&.last
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected
  def after_inactive_sign_up_path_for(resource)
    login_path
  end
end

app/controllers/reports/short_urls_controller.rb
class Reports::ShortUrlsController < AuthorizableController
  before_action :check_short_url, only: :show

  def index
    @short_url_stats = ShortUrlClickStats.new(user_id: current_user.id, since: Time.at(0)).results
  end

  def show
    @url_clicks = UrlClick.where(short_url_id: @short_url.id).map { |c| UrlClickPresenter.new(c) }
  end

  private

  def check_short_url
    @short_url = ShortUrl.find_by_url_hash(params[:id])
    render_404 unless @short_url
  end
end

app/controllers/urls_controller.rb
class UrlsController < AuthorizableController

  def index
    @urls = current_user.urls
  end

  def new
    @new_url = Url.new
  end

  def create
    outcome = Urls::Create.run(user: current_user, **create_url_params)

    if outcome.success?
      redirect_to url_path(outcome.result)
    else
      redirect_to new_url_path, notice: { message: outcome.errors.message.values.join("\n"), severity: 'error' }
    end
  end

  def show
    load_url
  end

  private

  def create_url_params
    params.require(:url).permit(:original_url).to_h
  end

  def load_url
    @url = Url.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to urls_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def home_link
    content_tag :a, href: '/' do
      'Home'
    end
  end
end

app/views/dashboard/index.html.erb
<div>
  <ul>
    <li><%= link_to 'Create link', new_url_path %></li>
    <li><%= link_to 'Links', urls_path %></li>
    <li><%= link_to 'Report', reports_short_urls_path %></li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shorturl</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if user_signed_in? %>
    <div>
        <%= button_to 'Logout', logout_path, method: :delete %>
    </div>
  <% end %>
    <main>
      <% if notice && notice['message'] %>
        <aside id="notice" class="<%= notice['severity'] == "error" ? "red_text" : "" %>"><%= notice['message'] %></aside>
        <aside id="alert"><%= alert %></aside>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/application_public.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shorturl</title>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Something went wrong!</h1>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/redirection/show.html.erb
<p>
  Sorry, we are not able to redirect for this url => <%= request_url %>
</p>

app/views/reports/short_urls/index.html.erb
<h1>Short Url Reports</h1>

<table>
  <thead>
    <tr>
      <td>Short url</td>
      <td>Long url</td>
      <td>Title</td>
      <td>Clicks count</td>
    </tr>
  </thead>

  <tbody>
    <% @short_url_stats.each do |stat| %>
      <tr>
        <td>
          <a href="<%= reports_short_url_path(stat.url_hash) %>" target="_blank">
            <%= ShortUrl.url_hash_to_url(stat.url_hash) %>
          </a>
        </td>
        <td><%= stat.original_url %></td>
        <td><%= stat.title %></td>
        <td><%= stat.click_count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= home_link %>

app/views/reports/short_urls/show.html.erb
<h1>Click events</h1>

<div>
  <p>
    Short url: <%= @short_url.to_url %>
  </p>
  <p>
    Original url: <%= @short_url.original_url %>
  </p>
  <p>
    Title: <%= @short_url.title %>
  </p>
</div>

<hr>

<div>
  <table>
    <thead>
      <tr>
        <td>Event time</td>
        <td>Ip</td>
        <td>Location</td>
      </tr>
    </thead>

    <tbody>
      <% @url_clicks.each do |click| %>
        <tr>
          <td><%= click.created_at %></td>
          <td><%= click.ip %></td>
          <td><%= click.address  %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<a href="<%= reports_short_urls_path %>">Back to urls report</a>

app/views/urls/index.html.erb
<div>
  Total urls count: <%= @urls.count %>
</div>

<ol>
  <% @urls.each do |url| %>
    <ul>
      <a href="<%= url_url(url) %>"><%= url.original_url %></a>
    </ul>
  <% end %>
</ol>

<%= home_link %>

app/views/urls/new.html.erb
<h1>New Short Url</h1>

<section class="url_form">
  <h2>Please Enter The Detail</h2>

  <%= form_for(@new_url) do |form| %>
    <div class="field">
      <%= form.label :original_url, 'Original Url' %>
      <%= form.text_field :original_url, id: :original_url %>
    </div>

    <div class="actions">
      <%= form.submit 'Submit' %>
    </div>
  <% end %>

  <%= home_link %>
</section>

app/views/urls/show.html.erb
<h1>Show url</h1>

<section>
  <p>
    <strong>Title:</strong>
    <%= @url.title %>
  </p>

  <p>
    <strong>Url:</strong>
    <%= @url.original_url %>
  </p>

  <h2>
    Short Urls (total: <%= @url.short_urls.size %>)
  </h2>

  <% @url.short_urls.each do |s_url| %>
    <ul>
      <li>
        <a href="<%= s_url.to_url %>" target="_blank"><%= s_url.to_url %></a>
      </li>
    </ul>
  <% end %>
</section>

<%= home_link %>